version: '3'
services:
  nfc_lock:
    build: ./nfc_lock
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    privileged: true
    env_file:
      - ./nfc_lock/.env
  nfc_activity:
    build: ./nfc_activity
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    privileged: true
    env_file:
      - ./nfc_activity/.env
  door_lock:
    build: ./door_lock
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./door_lock/.env
  db_service:
    build: ./db_service
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./db_service/.env
  db:
    image: postgres:latest
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./db/.env