version: '3'
services:
  nfc_lock:
    build: ./nfc_lock
    privileged: true
    env_file:
      - .env
  nfc_activity:
    build: ./nfc_activity
    privileged: true
    env_file:
      - .env
  door_lock:
    build: ./door_lock
    network_mode: host
  db_service:
    build: ./db_service
    ports:
      - 8001:8000
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env