name: Test

on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Test
        run: pytest